#!/usr/bin/env python3
"""7.6 Deployment — Architecture, working prototype, and consumption pattern.

Unlike a paper design, this script exercises a real prediction service
(`trufi_ds.api`, a FastAPI app backed by the Section 7.4 Random Forest
model) in-process via FastAPI's TestClient, and embeds the actual JSON
responses in the report — not hypothetical examples.

Output:
- reports/05_deployment/01_deployment_architecture.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import polars as pl
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).parent))

from trufi_ds.api import app
from trufi_ds.config import DEPLOY_REPORTS, MODEL_FEATURES_TABLE

# Two real example cells: a central hotspot and a peripheral low-demand
# cell, both taken from the actual data (not made up).
EXAMPLE_HOTSPOT_CELL = "888b2c8ae5fffff"
EXAMPLE_PERIPHERY_CELL = "888b2c80d5fffff"


def main() -> None:
    print("=" * 70)
    print("7.6 Deployment — Architecture and Prototype")
    print("=" * 70)

    print("\n[1/3] Exercising the prediction API in-process (FastAPI TestClient)...")
    with TestClient(app) as client:
        health = client.get("/health").json()
        print(f"  /health -> {health}")

        pred_hotspot = client.get("/predict", params={"cell": EXAMPLE_HOTSPOT_CELL}).json()
        pred_periphery = client.get("/predict", params={"cell": EXAMPLE_PERIPHERY_CELL}).json()
        pred_404 = client.get("/predict", params={"cell": "celda_inexistente"})
        top5 = client.get("/cells/top", params={"n": 5}).json()

        print(f"  /predict?cell={EXAMPLE_HOTSPOT_CELL} -> {pred_hotspot['predicted_n_queries_orig']} consultas")
        print(f"  /predict?cell={EXAMPLE_PERIPHERY_CELL} -> {pred_periphery['predicted_n_queries_orig']} consultas")
        print(f"  /predict?cell=celda_inexistente -> HTTP {pred_404.status_code}")
        print(f"  /cells/top?n=5 -> {[c['h3_cell'] for c in top5['top_cells']]}")

    # Known caveat: the hotspot's own lag-1 is deflated because the very
    # last training week (2024-W23) is the partial-data artifact documented
    # in 7.5 (03_error_analysis.md §2/§4) — verify and quantify it here so
    # the report states a measured fact, not a guess.
    lag1_hotspot = pred_hotspot["features_used"]["lag1_n_queries_orig"]
    roll_mean4_hotspot = pred_hotspot["features_used"]["roll_mean4_n_queries_orig"]
    lag1_is_deflated = lag1_hotspot < 0.3 * roll_mean4_hotspot
    print(f"\n  lag1={lag1_hotspot:.0f} vs. roll_mean4={roll_mean4_hotspot:.0f} for {EXAMPLE_HOTSPOT_CELL} -> deflated: {lag1_is_deflated}")

    print("\n[2/3] Confirming API feature parity with training-time engineering...")
    features_df = pl.read_parquet(MODEL_FEATURES_TABLE)
    n_cells = features_df.select("h3_cell").n_unique()
    max_week_idx = features_df.select(pl.col("week_idx").max()).item()
    print(f"  Feature store: {n_cells} celdas, semana más reciente = week_idx {max_week_idx}")

    # ── Report ──────────────────────────────────────────────────────────────
    print("\n[3/3] Writing report...")
    DEPLOY_REPORTS.mkdir(parents=True, exist_ok=True)
    report_path = DEPLOY_REPORTS / "01_deployment_architecture.md"

    report = f"""# 7.6.1-7.6.3 Deployment Architecture and Prototype

Generated by: `src/24_deployment_architecture.py`

## 1. Cómo se usaría el resultado en un contexto real

El resultado del modelo — demanda de consultas esperada por celda H3 y
semana — es una **capa analítica de priorización territorial**, no un
reemplazo de decisión humana. Dos usos concretos, ambos ya respaldados por
hallazgos de fases anteriores:

1. **Priorización de intervención de cobertura GTFS**: cruzando la
   predicción de demanda con `pct_uncovered_orig` (Sección 7.3.7) y el
   hallazgo H1 (Sección 7.5: la periferia tiene una brecha de cobertura
   significativamente mayor), el equipo de planificación de transporte
   puede rankear celdas por "demanda esperada × falta de cobertura" en vez
   de revisar las 1,552 celdas manualmente.
2. **Monitoreo de demanda emergente**: como el modelo preserva el ranking
   espacial de celdas (Spearman ρ=0.877, Sección 7.5 `02_results_analysis.md`
   §3), sirve para detectar qué celdas están *subiendo* de posición en el
   ranking semana a semana — señal temprana de una zona en expansión antes
   de que el volumen absoluto sea grande.

No se propone automatizar decisiones de ruteo: el MAE de test (10.19,
o 5.91 en semanas completas — Sección 7.5) implica error real por celda,
y el propio hallazgo H2 (Sección 7.5) muestra que la ventaja del modelo se
concentra en celdas de alta demanda, no en todas.

## 2. Prototipo: servicio de predicción (FastAPI)

Se implementó un **servicio real y ejecutable**, no solo un diagrama:
`src/trufi_ds/api.py`, que carga el modelo final (`models/random_forest.pkl`,
Sección 7.4) y `data/processed/model_features.parquet` para reconstruir,
para cualquier celda, el vector de features de la *semana siguiente a la
última observada* — usando exactamente la misma lógica de ingeniería de
características que `18_model_training.py` (perfil territorial, centralidad,
estacionalidad cíclica, variables autoregresivas), no una aproximación.

```bash
uv run uvicorn trufi_ds.api:app --reload --port 8000
```

### Arquitectura

```mermaid
flowchart TD
    A["GTFS feed (Mobility Database)"] -->|"run_update_pipeline.py, semanal"| B["data/raw/gtfs/"]
    C["Exportaciones de consultas<br/>(backend Trufi App)"] --> D["data/interim/queries.parquet"]
    B --> E["13_gtfs_coverage.py"]
    D --> E
    E --> F["15_indicators_table.py"]
    F --> G["data/processed/indicators_table.parquet"]
    G -->|"18_model_training.py<br/>(reentrenamiento trimestral)"| H["models/random_forest.pkl"]
    G -->|"feature engineering<br/>(18_model_training.py)"| I["data/processed/model_features.parquet"]
    H --> J["trufi_ds.api (FastAPI)"]
    I --> J
    J -->|"GET /predict?cell=..."| K["Equipo de planificación<br/>(dashboard / script / curl)"]
    J -->|"GET /cells/top?n=..."| K
    L["25_monitoring_plan.py"] -.->|"vigila"| J
```

Cada caja ya existe como código en este repo — el diagrama documenta cómo
se conectarían en producción, no un plan aspiracional.

## 3. Cómo se consumiría (ejemplos reales, no hipotéticos)

Los siguientes son **responses reales** obtenidos ejecutando el servicio
en proceso (`fastapi.testclient.TestClient`) contra los datos y el modelo
actuales de este repositorio — no ejemplos inventados.

### `GET /health`

```json
{json.dumps(health, indent=2, ensure_ascii=False)}
```

### `GET /predict?cell={EXAMPLE_HOTSPOT_CELL}` (celda central, alta demanda)

```json
{json.dumps(pred_hotspot, indent=2, ensure_ascii=False)}
```

### `GET /predict?cell={EXAMPLE_PERIPHERY_CELL}` (celda periférica, baja demanda)

```json
{json.dumps(pred_periphery, indent=2, ensure_ascii=False)}
```

### `GET /predict?cell=celda_inexistente` → error controlado

HTTP {pred_404.status_code}: `{pred_404.json()}`

### `GET /cells/top?n=5` — priorización territorial

```json
{json.dumps(top5, indent=2, ensure_ascii=False)}
```

## Limitación operativa detectada al construir el prototipo

Al probar `/predict` sobre la celda hotspot `{EXAMPLE_HOTSPOT_CELL}`, su
`lag1_n_queries_orig` (heredado de la última semana observada, 2024-W23)
resulta **{lag1_hotspot:.0f}**, muy por debajo de su media móvil de 4
semanas (**{roll_mean4_hotspot:.0f}**) — {'confirmado' if lag1_is_deflated else 'no confirmado'}
como el mismo artefacto de semana parcial documentado en la Sección 7.5
(`03_error_analysis.md` §2/§4): **2024-W23 es la última semana del dataset
completo, y es en sí misma una semana parcial** (~11h de datos). Esto
significa que **la primera predicción en vivo tras este dataset heredará
esa misma contaminación de lag-1** para todas las celdas, no solo para el
ejemplo mostrado.

**Recomendación antes de un primer despliegue real**: completar (backfill)
la semana 2024-W23 con datos reales de esa semana calendario completa antes
de servir la primera predicción en producción, o aceptar explícitamente un
primer ciclo de error elevado — documentado aquí en vez de descubierto en
producción.

## Evidencia

- Servicio: `src/trufi_ds/api.py`
- Script: `src/24_deployment_architecture.py`
- Modelo: `models/random_forest.pkl`
- Datos: `data/processed/model_features.parquet`
"""

    report_path.write_text(report)
    print(f"\nReport: {report_path}")


if __name__ == "__main__":
    main()
