#!/usr/bin/env python3
"""7.6.4 Monitoring and Retraining Plan.

Derives concrete, data-grounded monitoring thresholds and a retraining
cadence from the actual historical error distribution (Sections 7.4-7.5),
rather than proposing arbitrary numbers. Also turns the partial-week data
artifact discovered in `23_error_analysis.py` into a concrete pipeline
check, since that failure mode already happened once in this project.

Output:
- reports/05_deployment/02_monitoring_plan.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import polars as pl

sys.path.insert(0, str(Path(__file__).parent))

from trufi_ds.config import (
    CV_WINDOW_WEEKS,
    DEPLOY_REPORTS,
    MOBILITY_DB_UPDATE_INTERVAL_DAYS,
    MODEL_FEATURES_TABLE,
    MODEL_PREDICTIONS_TABLE,
)

MODEL_NAME = "random_forest"
PARTIAL_WEEKS = {78, 83}  # Section 7.5, 23_error_analysis.py


def main() -> None:
    print("=" * 70)
    print("7.6.4 Monitoring and Retraining Plan")
    print("=" * 70)

    predictions = pl.read_parquet(MODEL_PREDICTIONS_TABLE)
    test_rf = predictions.filter((pl.col("split") == "test") & (pl.col("model") == MODEL_NAME))
    test_rf = test_rf.with_columns((pl.col("y_true") - pl.col("y_pred")).abs().alias("abs_err"))

    print("\n[1/3] Deriving an alert threshold from the real test-week MAE distribution...")
    weekly_mae = test_rf.group_by("week_idx").agg(pl.col("abs_err").mean().alias("mae_week")).sort("week_idx")
    clean = weekly_mae.filter(~pl.col("week_idx").is_in(list(PARTIAL_WEEKS)))
    clean_vals = clean.get_column("mae_week").to_numpy()

    mean_clean = float(clean_vals.mean())
    std_clean = float(clean_vals.std(ddof=1))
    alert_threshold = mean_clean + 2 * std_clean
    max_clean = float(clean_vals.max())

    print(f"  Semanas de test limpias (sin artefacto parcial): {len(clean_vals)}")
    print(f"  MAE semanal: media={mean_clean:.2f}, std={std_clean:.2f}, max={max_clean:.2f}")
    print(f"  Umbral de alerta propuesto (media + 2·std): {alert_threshold:.2f}")

    print("\n[2/3] Reference weekly demand volume for pipeline sanity checks...")
    weekly_volume = (
        pl.read_parquet(str(MODEL_FEATURES_TABLE))
        .group_by("week_idx")
        .agg(pl.col("n_queries_orig").sum().alias("total"))
        .sort("week_idx")
    )
    # Use a recent window (not the full history) for the volume reference:
    # Section 7.2.8 documented sustained demand growth, so an all-time
    # median understates what a "normal" week looks like *now* — a
    # detection floor built on it would be too lax to catch a real drop.
    max_week_idx = weekly_volume.select(pl.col("week_idx").max()).item()
    recent_window = weekly_volume.filter(pl.col("week_idx") > max_week_idx - CV_WINDOW_WEEKS)
    normal_weeks = recent_window.filter(~pl.col("week_idx").is_in(list(PARTIAL_WEEKS)))
    median_volume = float(normal_weeks.get_column("total").median())
    volume_floor = 0.3 * median_volume
    print(f"  Volumen semanal normal (mediana, últimas {CV_WINDOW_WEEKS} semanas no parciales): {median_volume:,.0f} consultas")
    print(f"  Piso de completitud propuesto (30% de la mediana): {volume_floor:,.0f} consultas")
    print("  (Con este piso, 2024-W18 [909] y 2024-W23 [1,367] se habrían marcado incompletas de inmediato)")

    print("\n[3/3] Writing report...")
    DEPLOY_REPORTS.mkdir(parents=True, exist_ok=True)
    report_path = DEPLOY_REPORTS / "02_monitoring_plan.md"

    report = f"""# 7.6.4 Monitoring and Retraining Plan

Generated by: `src/25_monitoring_plan.py`

Los umbrales de esta sección se derivan de la distribución real de error y
de volumen de este proyecto (Secciones 7.4-7.5), no son valores arbitrarios.

## 1. Actualización de datos (GTFS): semanal

Ya implementado: `run_update_pipeline.py` verifica la antigüedad del feed
GTFS contra `MOBILITY_DB_UPDATE_INTERVAL_DAYS = {MOBILITY_DB_UPDATE_INTERVAL_DAYS}`
días y, si corresponde, descarga el feed actualizado (`gtfs_download.py`),
regenera cobertura (`13_gtfs_coverage.py`), la tabla de indicadores
(`15_indicators_table.py`) y la partición train/test (`17_train_test_split.py`).

```bash
uv run src/run_update_pipeline.py            # respeta el intervalo de 7 días
uv run src/run_update_pipeline.py --force    # fuerza actualización inmediata
```

**Falta conectar** (no implementado en este pipeline): tras actualizar
`indicators_table.parquet`, regenerar también `model_features.parquet`
(la lógica de `18_model_training.py::build_feature_table`) para que las
predicciones en vivo usen el perfil territorial y los rezagos más
recientes. Es una extensión directa, no una reescritura.

## 2. Reentrenamiento del modelo: trimestral

**Justificación**: la validación cruzada de ventanas deslizantes (Sección
7.4.3) usa una ventana de `CV_WINDOW_WEEKS = {CV_WINDOW_WEEKS}` semanas
(~3 meses) como la granularidad a la que el modelo ya demostró generalizar
razonablemente. Reentrenar con esa misma cadencia — no más seguido, no
menos — mantiene el modelo alineado con la tendencia de crecimiento
sostenido documentada en la Sección 7.2.8, sin reentrenar sobre ventanas
más cortas que las que la validación real cubrió.

```bash
for i in 18 19 20; do uv run src/${{i}}_*.py; done
```

**Trigger de reentrenamiento anticipado** (adicional al calendario
trimestral): si el MAE semanal en producción supera el umbral de alerta
(§3) durante 2 semanas consecutivas, reentrenar de inmediato en vez de
esperar al ciclo trimestral — señal de que la relación demanda↔condiciones
territoriales se movió más rápido de lo esperado.

## 3. Monitoreo de error: umbral derivado de datos reales

Las {len(clean_vals)} semanas de test "limpias" (excluyendo el artefacto de
semanas parciales, Sección 7.5) dan la distribución de referencia:

| Estadístico | Valor |
|-------------|-------|
| MAE semanal medio | {mean_clean:.2f} |
| Desviación estándar | {std_clean:.2f} |
| Máximo observado | {max_clean:.2f} |
| **Umbral de alerta (media + 2·σ)** | **{alert_threshold:.2f}** |

**Regla de monitoreo**: calcular el MAE de la semana más reciente
(prediction hecha la semana anterior vs. demanda real ya observada) cada
vez que se actualicen los datos. Si supera {alert_threshold:.2f}
consultas/semana, investigar antes de servir la siguiente predicción —
no descartar automáticamente como ruido, dado que la Sección 7.5 ya mostró
que un error inusualmente alto puede señalar un problema de datos real
(no del modelo).

## 4. Chequeo de completitud de datos (lección de la Sección 7.5)

La Sección 7.5 (`23_error_analysis.py`) encontró **dos semanas de test
que en realidad eran fragmentos de un día**, no semanas completas —
un artefacto de cobertura de exportación no detectado hasta la fase de
evaluación. Esto se traduce directamente en un chequeo de pipeline
concreto que no existía antes:

| Estadístico | Valor |
|-------------|-------|
| Volumen semanal normal (mediana, últimas {CV_WINDOW_WEEKS} semanas no parciales) | {median_volume:,.0f} consultas |
| **Piso de completitud propuesto (30% de la mediana)** | **{volume_floor:,.0f} consultas** |

**Regla propuesta**: antes de tratar una semana como completa (para
entrenamiento, evaluación o como fuente de `lag1` en producción), verificar
que su volumen total de consultas supere {volume_floor:,.0f}. Con este
piso, las semanas 2024-W18 (909 consultas) y 2024-W23 (1,367 consultas) se
habrían marcado como incompletas automáticamente, en vez de descubrirse
manualmente durante el análisis de errores. Una semana marcada incompleta
debería excluirse del cálculo de métricas y **no usarse como `lag1`** para
la predicción de la semana siguiente (ver limitación documentada en
`01_deployment_architecture.md`).

## 5. Qué monitorear en producción (resumen)

| Métrica | Frecuencia | Umbral / acción |
|---------|------------|-------------------|
| Volumen semanal total de consultas | Semanal | < {volume_floor:,.0f} → marcar semana incompleta, excluir de `lag1` |
| MAE semanal (predicción vs. real) | Semanal | > {alert_threshold:.2f} por 2 semanas seguidas → reentrenar antes del ciclo trimestral |
| Actualización GTFS | Semanal (automático) | `run_update_pipeline.py`, ya implementado |
| Reentrenamiento completo | Trimestral (calendario) | `18_model_training.py` → `20_feature_importance.py` |
| Cobertura GTFS agregada (`pct_uncovered_orig`) | Trimestral (con reentrenamiento) | Cambio brusco → revisar si el feed GTFS cambió de forma significativa |

## Evidencia

- Script: `src/25_monitoring_plan.py`
- Datos: `data/processed/model_predictions.parquet`, `model_features.parquet`
- Pipeline de actualización existente: `src/run_update_pipeline.py`
"""

    report_path.write_text(report)
    print(f"\nReport: {report_path}")


if __name__ == "__main__":
    main()
